build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related PROD APIs"
  contactDetails:
    name: "juan david"
    email: "prod@juandavyc.com"
  onCallSupport:
    - (57) 300-000-0000
    - (57) 300-000-0000