build:
  version: "1.0"

loans:
  message: "Welcome to Bank loans related PROD APIs"
  contactDetails:
    name: "juan david"
    email: "prod@juandavyc.com"
  onCallSupport:
    - (57) 300-000-0000
    - (57) 300-000-0000